name: Auto Push to 5nxtnxtnxt Repo(Vercel Deployment Repo)

on:
  push:
    branches:
      - main

jobs:
  push-to-personal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to personal repository
        env:
          PERSONAL_REPO: https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/5nxtnxtnxt/RunningMate.git
        run: |
          git remote add personal $PERSONAL_REPO
          git push personal main
